# Generated by Django 4.0.2 on 2022-03-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appoint',
        ),
    ]
